### ISSUE TITLE
Image source not readable

### ISSUE THREAD

**Issue by f-liva** [ebess/advanced-nova-media-library#182]
Using Amazon S3 in a public bucket, the file is uploaded, but Nova's form is not submitted because a red error popup is shown with: "Image source not readable".

Here the log:

```
[2020-06-24 13:12:28] local.ERROR: Image source not readable {"userId":1,"exception":"[object] (Intervention\\Image\\Exception\\NotReadableException(code: 0): Image source not readable at D:\\Progetti\\laravel-maca\\vendor\\intervention\\image\\src\\Intervention\\Image\\AbstractDecoder.php:346)
[stacktrace]
#0 D:\\Progetti\\laravel-maca\\vendor\\intervention\\image\\src\\Intervention\\Image\\AbstractDriver.php(66): Intervention\\Image\\AbstractDecoder->init('30/1174693_1020...')
#1 D:\\Progetti\\laravel-maca\\vendor\\intervention\\image\\src\\Intervention\\Image\\ImageManager.php(54): Intervention\\Image\\AbstractDriver->init('30/1174693_1020...')
#2 D:\\Progetti\\laravel-maca\\vendor\\intervention\\image\\src\\Intervention\\Image\\ImageManagerStatic.php(58): Intervention\\Image\\ImageManager->make('30/1174693_1020...')
#3 D:\\Progetti\\laravel-maca\\vendor\\spatie\\image\\src\\Image.php(101): Intervention\\Image\\ImageManagerStatic::make('30/1174693_1020...')
#4 D:\\Progetti\\laravel-maca\\app\\Listeners\\StoreMediaDimensions.php(32): Spatie\\Image\\Image->getWidth()
#5 [internal function]: App\\Listeners\\StoreMediaDimensions->handle(Object(Spatie\\MediaLibrary\\MediaCollections\\Events\\MediaHasBeenAdded))
#6 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(388): call_user_func_array(Array, Array)
#7 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(218): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Spatie\\\\MediaLib...', Array)
#8 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\helpers.php(476): Illuminate\\Events\\Dispatcher->dispatch('Spatie\\\\MediaLib...')
#9 D:\\Progetti\\laravel-maca\\vendor\\spatie\\laravel-medialibrary\\src\\MediaCollections\\Filesystem.php(31): event(Object(Spatie\\MediaLibrary\\MediaCollections\\Events\\MediaHasBeenAdded))
#10 D:\\Progetti\\laravel-maca\\vendor\\spatie\\laravel-medialibrary\\src\\MediaCollections\\FileAdder.php(386): Spatie\\MediaLibrary\\MediaCollections\\Filesystem->add('C:\\\\Users\\\\fede9\\\\...', Object(Spatie\\MediaLibrary\\MediaCollections\\Models\\Media), '1174693_1020119...')
#11 D:\\Progetti\\laravel-maca\\vendor\\spatie\\laravel-medialibrary\\src\\MediaCollections\\FileAdder.php(372): Spatie\\MediaLibrary\\MediaCollections\\FileAdder->processMediaItem(Object(App\\Stage), Object(Spatie\\MediaLibrary\\MediaCollections\\Models\\Media), Object(Spatie\\MediaLibrary\\MediaCollections\\FileAdder))
#12 D:\\Progetti\\laravel-maca\\vendor\\spatie\\laravel-medialibrary\\src\\MediaCollections\\FileAdder.php(298): Spatie\\MediaLibrary\\MediaCollections\\FileAdder->attachMedia(Object(Spatie\\MediaLibrary\\MediaCollections\\Models\\Media))
#13 D:\\Progetti\\laravel-maca\\vendor\\ebess\\advanced-nova-media-library\\src\\Fields\\Media.php(194): Spatie\\MediaLibrary\\MediaCollections\\FileAdder->toMediaCollection('photos')
#14 [internal function]: Ebess\\AdvancedNovaMediaLibrary\\Fields\\Media->Ebess\\AdvancedNovaMediaLibrary\\Fields\\{closure}(Object(Illuminate\\Http\\UploadedFile), 0)
#15 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Collection.php(638): array_map(Object(Closure), Array, Array)
#16 D:\\Progetti\\laravel-maca\\vendor\\ebess\\advanced-nova-media-library\\src\\Fields\\Media.php(200): Illuminate\\Support\\Collection->map(Object(Closure))
#17 D:\\Progetti\\laravel-maca\\vendor\\ebess\\advanced-nova-media-library\\src\\Fields\\Media.php(155): Ebess\\AdvancedNovaMediaLibrary\\Fields\\Media->addNewMedia(Object(Laravel\\Nova\\Http\\Requests\\UpdateResourceRequest), Array, Object(App\\Stage), 'photos')
#18 D:\\Progetti\\laravel-maca\\vendor\\ebess\\advanced-nova-media-library\\src\\Fields\\Media.php(145): Ebess\\AdvancedNovaMediaLibrary\\Fields\\Media->handleMedia(Object(Laravel\\Nova\\Http\\Requests\\UpdateResourceRequest), Object(App\\Stage), 'photos', Array)
#19 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\HigherOrderCollectionProxy.php(60): Ebess\\AdvancedNovaMediaLibrary\\Fields\\Media->Ebess\\AdvancedNovaMediaLibrary\\Fields\\{closure}()
#20 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\HigherOrderCollectionProxy.php(60): Closure->__invoke()
#21 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Traits\\EnumeratesValues.php(202): Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}(Object(Closure), 0)
#22 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\HigherOrderCollectionProxy.php(61): Illuminate\\Support\\Collection->each(Object(Closure))
#23 D:\\Progetti\\laravel-maca\\vendor\\laravel\
ova\\src\\Http\\Controllers\\ResourceUpdateController.php(38): Illuminate\\Support\\HigherOrderCollectionProxy->__call('__invoke', Array)
#24 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Concerns\\ManagesTransactions.php(28): Laravel\\Nova\\Http\\Controllers\\ResourceUpdateController->Laravel\\Nova\\Http\\Controllers\\{closure}(Object(Illuminate\\Database\\MySqlConnection))
#25 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\DatabaseManager.php(367): Illuminate\\Database\\Connection->transaction(Object(Closure))
#26 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(261): Illuminate\\Database\\DatabaseManager->__call('transaction', Array)
#27 D:\\Progetti\\laravel-maca\\vendor\\laravel\
ova\\src\\Http\\Controllers\\ResourceUpdateController.php(41): Illuminate\\Support\\Facades\\Facade::__callStatic('transaction', Array)
#28 [internal function]: Laravel\\Nova\\Http\\Controllers\\ResourceUpdateController->handle(Object(Laravel\\Nova\\Http\\Requests\\UpdateResourceRequest), 'stages', '1')
#29 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): call_user_func_array(Array, Array)
#30 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('handle', Array)
#31 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Laravel\\Nova\\Http\\Controllers\\ResourceUpdateController), 'handle')
#32 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(196): Illuminate\\Routing\\Route->runController()
#33 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(685): Illuminate\\Routing\\Route->run()
#34 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 D:\\Progetti\\laravel-maca\\vendor\\laravel\
ova\\src\\Http\\Middleware\\Authorize.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 D:\\Progetti\\laravel-maca\\vendor\\laravel\
ova\\src\\Http\\Middleware\\BootTools.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\BootTools->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 D:\\Progetti\\laravel-maca\\vendor\\laravel\
ova\\src\\Http\\Middleware\\DispatchServingNovaEvent.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\DispatchServingNovaEvent->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 D:\\Progetti\\laravel-maca\\vendor\\laravel\
ova\\src\\Http\\Middleware\\Authenticate.php(31): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#52 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(687): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#59 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#60 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(628): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#61 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#62 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(165): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#63 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#64 D:\\Progetti\\laravel-maca\\vendor\\laravel\
ova\\src\\Http\\Middleware\\ServeNova.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 D:\\Progetti\\laravel-maca\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#75 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#76 D:\\Progetti\\laravel-maca\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#77 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#78 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#79 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#80 D:\\Progetti\\laravel-maca\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#81 D:\\Progetti\\laravel-maca\\public\\index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#82 {main}
"} 
```

**Comment by f-liva** [comment]
I found the issue

**Comment by FelipeMarcos** [comment]
How did you fix it?
