### ISSUE TITLE
SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "media" does not exist

### ISSUE THREAD

**Issue by xoco70** [ebess/advanced-nova-media-library#189]
Hi, 

After installing, I add the field:

            Files::make('Autorisations', 'autorisations'),

I have a field in db called `autorisations` and his type is `json`

I can see the field, but when I create / update, I see this message.

```
[2020-07-30 07:26:31] local.ERROR: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "media" does not exist
LINE 1: select * from "media" where "media"."model_id" = $1 and "med...
                      ^ (SQL: select * from "media" where "media"."model_id" = 1 and "media"."model_id" is not null and "media"."model_type" = App\Operation) {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42P01): SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"media\" does not exist
LINE 1: select * from \"media\" where \"media\".\"model_id\" = $1 and \"med...
                      ^ (SQL: select * from \"media\" where \"media\".\"model_id\" = 1 and \"media\".\"model_id\" is not null and \"media\".\"model_type\" = App\\Operation) at /home/julien/Code/acc/vendor/laravel/framework/src/Illuminate/Database/Connection.php:671)
[stacktrace]
#0 /home/julien/Code/acc/vendor/laravel/framework/src/Illuminate/Database/Connection.php(631): Illuminate\\Database\\Connection->runQueryCallback()
#1 /home/julien/Code/acc/vendor/laravel/framework/src/Illuminate/Database/Connection.php(339): Illuminate\\Database\\Connection->run()
#2 /home/julien/Code/acc/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2205): Illuminate\\Database\\Connection->select()
#3 /home/julien/Code/acc/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2193): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /home/julien/Code/acc/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2688): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 /home/julien/Code/acc/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2194): Illuminate\\Database\\Query\\Builder->onceWithColumns()
#6 /home/julien/Code/acc/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(539): Illuminate\\Database\\Query\\Builder->get()
#7 /home/julien/Code/acc/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(523): Illuminate\\Database\\Eloquent\\Builder->getModels()
#8 /home/julien/Code/acc/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/MorphMany.php(17): Illuminate\\Database\\Eloquent\\Builder->get()
#9 /home/julien/Code/acc/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(448): Illuminate\\Database\\Eloquent\\Relations\\MorphMany->getResults()
#10 /home/julien/Code/acc/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(420): Illuminate\\Database\\Eloquent\\Model->getRelationshipFromMethod()
#11 /home/julien/Code/acc/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(375): Illuminate\\Database\\Eloquent\\Model->getRelationValue()
#12 /home/julien/Code/acc/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1633): Illuminate\\Database\\Eloquent\\Model->getAttribute()
#13 /home/julien/Code/acc/vendor/spatie/laravel-medialibrary/src/InteractsWithMedia.php(476): Illuminate\\Database\\Eloquent\\Model->__get()
#14 /home/julien/Code/acc/vendor/spatie/laravel-medialibrary/src/MediaCollections/MediaRepository.php(32): App\\Operation->loadMedia()
#15 /home/julien/Code/acc/vendor/spatie/laravel-medialibrary/src/InteractsWithMedia.php(229): Spatie\\MediaLibrary\\MediaCollections\\MediaRepository->getCollection()
#16 /home/julien/Code/acc/vendor/ebess/advanced-nova-media-library/src/Fields/Media.php(233): App\\Operation->getMedia()
#17 /home/julien/Code/acc/vendor/laravel/nova/src/Fields/FieldCollection.php(51): Ebess\\AdvancedNovaMediaLibrary\\Fields\\Media->resolve()
#18 /home/julien/Code/acc/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(202): Laravel\\Nova\\Fields\\FieldCollection->Laravel\\Nova\\Fields\\{closure}()
#19 /home/julien/Code/acc/vendor/laravel/nova/src/Fields/FieldCollection.php(53): Illuminate\\Support\\Collection...
```

It seems that the migration is not running, I have no table media in my DB

I use Postgres.

I have tried to uninstall / reinstall plugin, but same problem.

What should I do ?

**Comment by narcisonunez** [comment]
You need to do this:

```
composer require "spatie/laravel-medialibrary:^8.0.0"
php artisan vendor:publish --provider="Spatie\MediaLibrary\MediaLibraryServiceProvider" --tag="migrations"
php artisan migrate
```

Done!!

**Comment by xoco70** [comment]
thanks ! Files:: is much better than builtin one !
